### ISSUE TITLE
FoldIt test data 

### ISSUE THREAD

**Issue by ClaraTmsn** [nadeemlab/CEP#12]
Hi,
I would like to get the IoU and Dice metrics as done in the FoldIt paper (Table 1), however I cannot find the two sequences that you used to get these metrics. Could you please tell me where I could find them or are they not available?
Thank you

**Comment by sanadeem** [comment]
Thank you for your interest in CEP/FoldIt. Unfortunately we didn’t release the textured VC datasets/sequences with ground truth fold annotations. We will discuss internally and see if these can be released too in the future.
