### ISSUE TITLE
train foldit model

### ISSUE THREAD

**Issue by NowJzy** [nadeemlab/CEP#4]
Hello, I have some question about the training command. Does "foldit_model_name" in training command represent the concrete model name? Like 'foldit_model_public/latest_net_G_A.pth'.

**Comment by shmathew511** [comment]
When training, the method used is defined by the -model argument, and a directory should appear inside the checkpoints folder with the name from the -name argument (ie: "foldit_model_name"). This directory stores the model weights in files such as "latest_net_G_A.pth". When testing, it uses the -name argument to find the directory with the model weights from the corresponding training session. 

Essentially, you can put any name you want, and when you want to test just remember to use the same name to get the weights from that training session.

**Comment by NowJzy** [comment]
> When training, the method used is defined by the -model argument, and a directory should appear inside the checkpoints folder with the name from the -name argument (ie: "foldit_model_name"). This directory stores the model weights in files such as "latest_net_G_A.pth". When testing, it uses the -name argument to find the directory with the model weights from the corresponding training session.
> 
> Essentially, you can put any name you want, and when you want to test just remember to use the same name to get the weights from that training session.

Thanks for your concrete reply. And there is another problem while testing, I'd like to know how to split the test datasets, while the datasets offered contain 9 subfolds. Should I split them into valA, valB and valC ?

**Comment by shmathew511** [comment]
Can you provide me the model you are trying to train/test and the dataset?
