### ISSUE TITLE
About augment in the CLTS-GAN

### ISSUE THREAD

**Issue by ErisGe** [nadeemlab/CEP#8]
When I read your paper of CLTS-GAN, I found that there was an experiment in which one OC diagram was used to enhance the other one, but I could not find the corresponding part in your code. Could you please tell me how to test this part?
Besides, how does the triple augment work in the paper?
Looking forward to your reply!

**Comment by ErisGe** [comment]
I have written the code to enhance with another graph, but I still have some doubts about the triple enhancement, is it to reuse the variable to generate the OC graph three times?

**Comment by shmathew511** [comment]
I am a bit unclear on which graph you are referring to. Can you specify which the figure number?

**Comment by ErisGe** [comment]
Table 1
w/3 Aug

**Comment by sanadeem** [comment]
I guess you are talking about the PraNet experiment with 3 color/lighting augmentations (as seen in Figure 5). These OC images with the corresponding color/lighting augmentations are available on our CLTS-GAN zenodo. Yes, you will run the model 3 times to generate three different color/lighting variations for a given OC image.
