### ISSUE TITLE
How to control the texture and specular highlight separately in CLTS-GAN?

### ISSUE THREAD

**Issue by ErisGe** [nadeemlab/CEP#9]
I noticed in your paper that high intensity specular reflections can be extracted and stored in separate parameters by a loss, and I would like to know exactly how this is done? Is it convenient for you to provide this part of the code?

**Comment by shmathew511** [comment]
To change the color and texture independently, you can use the --freeze_color and --freeze_texture flags during testing

**Comment by ErisGe** [comment]
Sorry, but I think you misunderstood what I meant. 
--freeze_texture flag can control both texture and specular highlight. I want to separate them, and use two flags to control texture and specular highlight separately.

**Comment by sanadeem** [comment]
That's not currently possible. We left it as future work as can be seen in the discussion section. In the future, we are planning to use disentangled representations to let the user control all four attributes independently, rather than color/lighting and texture/specular.
